spring:
  application:
    name: ttb_api
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.172.204:3306/ttb_bi
    username: ttb_bi
    password: qwer1234

server:
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      store-type: none
      cookie:
        max-age: 2592000
        domain: try2best.com

